### PR TITLE
Allow nette/utils ^4.0.0

### PR DESCRIPTION
**Pull request by jakubvojacek**

### CODE REVIEW

**Comment by nextMJ** [comment]
Please pull. It still conflicts with my composer

```
    - contributte/monolog[v0.5.0, ..., v0.5.1] require nette/utils ^3.0.0 -> found nette/utils[v3.0.0, ..., v3.2.9] but it conflicts with your root composer.json require (^4.0).
```

**Comment by nextMJ** [comment]
> Please pull. It still conflicts with my composer
> 
> ```
>     - contributte/monolog[v0.5.0, ..., v0.5.1] require nette/utils ^3.0.0 -> found nette/utils[v3.0.0, ..., v3.2.9] but it conflicts with your root composer.json require (^4.0).
> ```

Sorry, forgot to mention the project owner :-) @f3l1x

**Comment by jakubvojacek** [comment]
He waits for all Nette packages to be updated to 4.x which, given how "rapid" development Nette is undergoing might be years

**Comment by f3l1x** [comment]
@nextMJ Merged.
@jakubvojacek Done ;-)

**Comment by nextMJ** [comment]
Great! Thanks to both of you :-)

**Pull request merged**
